import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { fileURLToPath } from 'node:url';
import { mkdir, writeFile } from 'node:fs/promises';

const base = (process.env.REGISTER_URL || 'http://127.0.0.1:8846').replace(/\/$/, '');
const shots = new URL('../../docs/qa/', import.meta.url);
await mkdir(shots, { recursive: true });
const browser = await chromium.launch({ headless: true });
const context = await browser.newContext({ viewport: { width: 1440, height: 1100 }, reducedMotion: 'reduce' });
const page = await context.newPage();
const errors = [], failures = [], external = [];
page.on('pageerror', e => errors.push(e.message));
page.on('requestfailed', r => failures.push(`${r.url()}: ${r.failure()?.errorText}`));
page.on('request', r => { if (new URL(r.url()).origin !== new URL(base).origin) external.push(r.url()); });
await page.goto(base);
await page.locator('.milestone').last().waitFor();
// A fresh lesson reveals only the Mine Law; unrevealed content has no keyboard routes.
assert.equal(await page.locator('.milestone').count(),1);
assert.equal(await page.locator('.milestone[data-event-id=mine1810]').count(),1);
assert.equal(await page.locator('.incident-step').count(),0);
assert.equal(await page.locator('.responsibility-phase').count(),0);
assert.equal(await page.locator('.timeline-position button').count(),1);
await page.screenshot({path:fileURLToPath(new URL('tijdlijn-opbouw-start.png',shots)),fullPage:true});
await page.emulateMedia({reducedMotion:'no-preference'});
await page.locator('.milestone[data-event-id=mine1810]').click();
assert.equal(await page.locator('.milestone').count(),2);
assert.match(await page.locator('.event-explanation h2').textContent(),/Mijnwet/);
assert.equal(await page.locator('.just-revealed .milestone-card').evaluate(el=>getComputedStyle(el).animationName),'lesson-card-enter');
await page.locator('.just-revealed .milestone-card').evaluate(el=>Promise.all(el.getAnimations().map(a=>a.finished)));
await page.screenshot({path:fileURLToPath(new URL('tijdlijn-opbouw-volgende.png',shots)),fullPage:true});
await page.locator('.milestone[data-event-id=mine1810]').click();
assert.equal(await page.locator('.milestone').count(),2,'Revisiting an earlier card revealed extra content');
await page.emulateMedia({reducedMotion:'reduce'});
await page.getByRole('button',{name:'Open docentantwoord',exact:true}).click();
await page.locator('.milestone[data-event-id=child1874]').click();
assert.equal(await page.locator('.milestone').count(),3);
assert.equal(await page.locator('.teacher-answer').count(),0);
assert.equal(await page.locator('.just-revealed .milestone-card').evaluate(el=>getComputedStyle(el).animationName),'none');
await page.locator('.milestone[data-event-id=safety1895]').click();
assert.equal(await page.locator('.milestone').count(),4);
assert.equal(await page.locator('.incident-step').count(),2,'Incident cases did not follow the revealed period');
assert.equal(await page.locator('.responsibility-phase').count(),2);
await page.locator('.milestone[data-event-id=law1980]').click();
await page.locator('.milestone[data-event-id=eu1989]').click();
await page.locator('.milestone[data-event-id=decision1997]').click();
assert.equal(await page.locator('.mini-step[data-mini-id=arie2023]').count(),0,'Later optional detail leaked before its period');
await page.locator('.milestone[data-event-id=law1999]').click();
assert.equal(await page.locator('.incident-step').count(),3);
await page.locator('.milestone[data-event-id=change2007]').click();
assert.equal(await page.locator('.milestone').count(),9);
assert.equal(await page.locator('.incident-step').count(),4);
await page.getByRole('button',{name:'Opnieuw beginnen ↺',exact:true}).click();
assert.equal(await page.locator('.milestone').count(),1);
assert.equal(await page.locator('.incident-step').count(),0);
assert.equal(await page.locator('.responsibility-phase').count(),0);
await page.getByRole('button',{name:/^Alle stappen/}).click();
assert.equal(await page.locator('.milestone').count(),1,'Changing detail level exposed future steps');
for(let count=1;count<17;count++){
  await page.locator('.milestone').last().click();
  assert.equal(await page.locator('.milestone').count(),count+1);
}
assert.equal(await page.locator('.milestone.minor').count(),8);
await page.getByRole('button',{name:'Opnieuw beginnen ↺',exact:true}).click();
await page.getByRole('button',{name:/^Hoofdmijlpalen/}).click();
await page.locator('.horizontal-track').focus();
await page.keyboard.press('ArrowRight');
assert.equal(await page.locator('.milestone').count(),2);
assert.match(await page.locator('.event-explanation h2').textContent(),/Kinderwet/);
await page.getByRole('button',{name:'Opnieuw beginnen ↺',exact:true}).click();
await page.getByRole('button',{name:'Toon alles',exact:true}).click();
assert.equal(await page.locator('.milestone').count(), 9);
assert.equal(await page.locator('.milestone.minor').count(), 0);
assert.equal(await page.locator('.teacher-answer').count(), 0);
await page.getByRole('button', { name: 'Open docentantwoord' }).click();
await page.locator('.teacher-answer').waitFor();
await page.getByRole('button', { name: 'Volgende gebeurtenis', exact: true }).click();
assert.equal(await page.locator('.teacher-answer').count(), 0);
assert.match(await page.locator('.event-explanation h2').textContent(), /Kinderwet/);
assert.equal(await page.locator('.mini-step').count(), 3);
await page.locator('.mini-step[data-mini-id=labour1889]').click();
assert.match(await page.locator('.event-explanation h2').textContent(), /Arbeidswet/);
assert.equal(await page.locator('.milestone[data-event-id=child1874]').getAttribute('aria-pressed'), 'true');
await page.locator('.mini-step[data-mini-id=labour1889]').focus();
await page.keyboard.press('ArrowRight');
assert.match(await page.locator('.event-explanation h2').textContent(), /Arbeidsinspectie/);
await page.locator('.parent-route button').click();
assert.match(await page.locator('.event-explanation h2').textContent(), /Kinderwet/);
await page.locator('.horizontal-track').focus();
await page.keyboard.press('ArrowRight');
assert.match(await page.locator('.event-explanation h2').textContent(), /Veiligheidswet 1895/);
// Test actual card bounds, including all long headings at classroom scale.
const assertCardsFit = async () => {
  const outside = await page.locator('.timeline-stage').evaluate(stage => {
    const bounds = stage.getBoundingClientRect();
    return [...stage.querySelectorAll('.milestone-card')].filter(card => {
      const rect = card.getBoundingClientRect();
      return rect.top < bounds.top - 1 || rect.bottom > bounds.bottom + 1;
    }).map(card => card.textContent);
  });
  assert.deepEqual(outside, [], 'Timeline card clipped');
  if(await page.locator('.responsibility-rail').count()){
    const overlap=await page.locator('.timeline-stage').evaluate(stage=>{
      const rail=stage.querySelector('.responsibility-rail').getBoundingClientRect();
      return [...stage.querySelectorAll('.milestone-card')].some(card=>card.getBoundingClientRect().top<rail.bottom+5);
    });
    assert.equal(overlap,false,'Development rail overlaps a lesson card');
  }
};
await assertCardsFit();
await page.getByRole('button', { name: /^Alle stappen/ }).click();
assert.equal(await page.locator('.milestone').count(), 17);
assert.equal(await page.locator('.milestone.minor').count(), 8);
await assertCardsFit();
await page.locator('.milestone[data-event-id=effect1983]').click();
await page.getByRole('button', { name: /^Hoofdmijlpalen/ }).click();
assert.equal(await page.locator('.milestone').count(), 9);
assert.match(await page.locator('.event-explanation h2').textContent(), /Arbowet wordt ingevoerd/);
assert.equal(await page.locator('.milestone[data-event-id=law1980]').getAttribute('aria-pressed'), 'true');
assert.equal(await page.locator('.mini-step').count(), 2);
await page.locator('.mini-step[data-mini-id=law1980]').click();
await page.getByRole('button', { name: 'Open docentantwoord' }).click();
await page.locator('.mini-step[data-mini-id=effect1983]').click();
assert.equal(await page.locator('.teacher-answer').count(), 0);
await page.locator('.milestone[data-event-id=eu1989]').click();
await page.locator('.mini-step[data-mini-id=implement1994]').click();
assert.match(await page.locator('.event-explanation h2').textContent(), /RI&E en preventie/);
await page.locator('.milestone[data-event-id=child1874]').click();
await page.screenshot({ path: fileURLToPath(new URL('tijdlijn-desktop.png', shots)), fullPage: true });
await page.getByRole('button', { name: 'Presenteren', exact: true }).click();
await assertCardsFit();
assert.equal(await page.locator('.timeline-view.presentation').count(), 1);
await page.screenshot({ path: fileURLToPath(new URL('tijdlijn-presentatie.png', shots)), fullPage: true });
await page.keyboard.press('Escape');
assert.equal(await page.locator('.timeline-view.presentation').count(), 0);
await page.getByRole('button', { name: 'Wetgeving & historie', exact: true }).click();
await page.locator('.legal-text .provision').first().waitFor();
assert.equal(await page.locator('.milestone').count(), 35);
assert.ok(await page.locator('.milestone.major').count() > 0);
assert.ok(await page.locator('.milestone.minor').count() > 0);
assert.ok(await page.locator('.milestone.unknown').count() > 0);
await page.getByRole('button', { name: /^Hoofdmijlpalen/ }).click();
assert.equal(await page.locator('.milestone:not(.major)').count(), 0);
assert.equal(await page.locator('.milestone[aria-pressed=true]').count(), 1);
// A subject search must find ARIE even while the user is looking at the Arbowet.
await page.getByLabel('Zoek wetswijziging', { exact: true }).fill('ARIE wijziging');
const arieResult=page.locator('.timeline-search-results>button').filter({hasText:'ARIE herziening'});
assert.equal(await arieResult.count(), 1);
assert.match(await arieResult.textContent(), /Arbobesluit/);
await arieResult.click();
await page.locator('.timeline-hero h1').filter({ hasText: 'Arbeidsomstandighedenbesluit' }).waitFor();
await page.locator('.milestone[aria-pressed=true]').filter({hasText:'ARIE herziening'}).waitFor();
assert.equal(await page.getByLabel('Peildatum', {exact:true}).inputValue(), '2023-01-01');
assert.equal(await page.locator('.milestone').count(), 95);
assert.match(await page.locator('.legal-event .event-explanation h2').textContent(), /ARIE herziening/);
assert.equal(await page.locator('.affected-articles').getByRole('button', {name:'Art. 2.5j Exploitatieverbod', exact:true}).count(), 1);
await assertCardsFit();
await page.locator('.affected-articles').getByRole('button', {name:/^Art\. 2\.5a /}).click();
await page.locator('main h2').filter({hasText:/veiligheidsbeheerssysteem/i}).waitFor();
assert.equal(await page.getByLabel('Peildatum', {exact:true}).inputValue(), '2023-01-01');
assert.equal(await page.locator('.milestone[aria-pressed=true]').filter({hasText:'ARIE herziening'}).count(), 1);
await page.getByLabel('Zoek wetswijziging', {exact:true}).fill('stb-2022-501');
assert.ok(await page.locator('.timeline-search-results>button').filter({hasText:'ARIE'}).count()>=2);
await page.getByLabel('Zoek wetswijziging', {exact:true}).fill('geenbestaandonderwerp');
assert.equal(await page.locator('.timeline-search-results>button').count(), 0);
await page.getByRole('button', {name:'Wis zoeken naar wetswijzigingen',exact:true}).click();
await page.getByRole('button', {name:/Arbeidsomstandighedenwet/}).click();
await page.locator('.timeline-hero h1').filter({hasText:'Arbeidsomstandighedenwet'}).waitFor();
await assertCardsFit();
await page.getByRole('button', {name:/^Hoofdmijlpalen/}).click();
await page.getByRole('button', { name: /Arbeidsomstandighedenbesluit/ }).click();
await page.locator('.legal-text').getByText('De werkgever legt de algemene doelstellingen', { exact: false }).waitFor();
await page.locator('.timeline-hero h1').filter({ hasText: 'Arbeidsomstandighedenbesluit' }).waitFor();
await page.locator('.milestone[aria-pressed=true]').waitFor();
assert.equal(await page.locator('.milestone:not(.major)').count(), 0);
await page.getByRole('button', { name: /^Alle wijzigingen/ }).click();
assert.equal(await page.locator('.milestone').count(), 95);
await page.getByLabel('Peildatum', { exact: true }).fill('2022-12-31');
await page.locator('main h2').getByText('Omstandigheidsfactoren', { exact: true }).waitFor();
await page.getByLabel('Peildatum', { exact: true }).fill('2023-01-01');
await page.locator('main h2').getByText('Aanvullende voorschriften', { exact: false }).waitFor();
await page.getByRole('button', { name: 'Vergelijk teksten', exact: true }).click();
await page.getByLabel('Vergelijken vanaf', { exact: true }).fill('2022-12-31');
await page.getByLabel('Vergelijken tot', { exact: true }).fill('2023-01-01');
assert.ok(await page.locator('.diff ins').count() > 0);
assert.ok(await page.locator('.diff del').count() > 0);
await page.getByRole('tab', { name: 'Toelichting', exact: true }).click();
await page.getByRole('button', { name: 'Volledige publicatie offline', exact: true }).first().click();
await page.getByRole('dialog', { name: 'Offline publicatie' }).waitFor();
assert.match(await page.locator('.publication-modal').textContent(), /stb-2022-501/);
await page.getByRole('button', { name: 'Sluiten ×', exact: true }).click();
await page.getByRole('tab', { name: 'Bron', exact: true }).click();
const raw = page.getByRole('link', { name: 'Open lokaal XML-bronbestand', exact: false });
const response = await context.request.get(new URL(await raw.getAttribute('href'),base).href);
assert.equal(response.status(), 200);
assert.match(await response.text(), /bwb-id="BWBR0008498"/);
await page.getByLabel('Tijdlijnbereik', { exact: true }).selectOption('article');
await page.getByRole('heading', { name: 'De geschiedenis van artikel 2.5', exact: true }).waitFor();
await page.locator('.milestone').filter({ hasText: '2023' }).first().click();
assert.equal(await page.getByLabel('Peildatum', { exact: true }).inputValue(), '2023-01-01');
assert.ok(await page.locator('.mini-step').count() >= 2);
assert.equal(await page.locator('.milestone[data-impact=unknown]').filter({ hasText: '2023' }).count(), 1);
const sourceStep=page.locator('.mini-step').filter({ hasText: 'stb-2022-501' }).first();
await sourceStep.click();
await page.getByRole('dialog', { name: 'Offline publicatie' }).waitFor();
await page.getByRole('button', { name: 'Sluiten ×', exact: true }).click();
await page.getByRole('button', { name: 'Offline publicatie stb-2022-501', exact: true }).click();
await page.getByRole('dialog', { name: 'Offline publicatie' }).waitFor();
await page.getByRole('button', { name: 'Sluiten ×', exact: true }).click();
await page.screenshot({ path: fileURLToPath(new URL('register-desktop.png', shots)), fullPage: true });
await page.getByRole('button', { name: 'Tijdlijn · lesdag 1', exact: true }).click();
await page.setViewportSize({ width: 390, height: 844 });
await page.locator('.milestone').first().waitFor();
await page.locator('.milestone[data-event-id=law1980]').click();
assert.equal(await page.locator('.mini-step').count(), 2);
await page.locator('.mini-step[data-mini-id=effect1983]').click();
assert.match(await page.locator('.event-explanation h2').textContent(), /Arbowet wordt ingevoerd/);
assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, 'Page overflows mobile viewport');
await assertCardsFit();
await page.screenshot({ path: fileURLToPath(new URL('tijdlijn-mobiel.png', shots)), fullPage: true });
await page.getByRole('button', {name:'Wetgeving & historie',exact:true}).click();
await page.getByLabel('Zoek wetswijziging', {exact:true}).fill('ARIE');
await page.locator('.timeline-search-results>button').filter({hasText:'ARIE herziening'}).click();
await page.locator('.milestone[aria-pressed=true]').filter({hasText:'ARIE herziening'}).waitFor();
const mobileOverflow=await page.evaluate(() => document.documentElement.scrollWidth > innerWidth);
if(mobileOverflow){
  await page.screenshot({path:fileURLToPath(new URL('arie-overflow.png',shots)),fullPage:true});
  console.log(await page.evaluate(()=>[...document.querySelectorAll('body *')].filter(e=>{
    const r=e.getBoundingClientRect();return r.right>innerWidth+1&&!e.closest('.horizontal-track,.mini-track,.timeline-position,.affected-articles');
  }).slice(0,18).map(e=>({element:e.tagName,classes:e.className,width:e.getBoundingClientRect().width,right:e.getBoundingClientRect().right,scrollWidth:e.scrollWidth,text:e.textContent?.slice(0,65)}))));
}
assert.equal(mobileOverflow, false, 'Subject results overflow mobile viewport');
await assertCardsFit();
await page.screenshot({ path: fileURLToPath(new URL('arie-mobiel.png', shots)), fullPage: true });
await page.setViewportSize({width:1440,height:1100});
await page.goto(base+'/?regeling=BWBR0008498&artikel=2.5&datum=2023-01-01');
await page.locator('.milestone[aria-pressed=true]').filter({hasText:'ARIE herziening'}).waitFor();
assert.equal(await page.getByLabel('Peildatum',{exact:true}).inputValue(),'2023-01-01');
await assertCardsFit();
await page.getByLabel('Zoek wetswijziging',{exact:true}).fill('ARIE');
await page.locator('.timeline-view').screenshot({path:fileURLToPath(new URL('arie-desktop.png',shots))});
await page.getByRole('button',{name:'Presenteren',exact:true}).click();
await assertCardsFit();
await page.keyboard.press('Escape');
// Lesson routes distinguish historical ARIE numbering and preserve a quiet main story.
await page.getByRole('button', {name:'Tijdlijn · lesdag 1',exact:true}).click();
await page.getByRole('button', {name:'Toon alles',exact:true}).click();
await page.locator('.milestone[data-event-id=decision1997]').click();
assert.equal(await page.locator('.milestone').count(), 9);
assert.equal(await page.locator('.mini-step').count(), 3);
await page.locator('.mini-step[data-mini-id=arie2004]').click();
assert.match(await page.locator('.event-topics').textContent(), /ARIE/);
const lessonRoutes=page.getByRole('region', {name:'Artikelroutes bij dit lesmoment'});
assert.match(await lessonRoutes.textContent(), /25 februari 2004/);
await lessonRoutes.getByRole('button', {name:/Aanvullende RI&E/}).click();
await page.locator('main h2').filter({hasText:/risico-inventarisatie/i}).waitFor();
assert.equal(await page.getByLabel('Peildatum',{exact:true}).inputValue(),'2004-02-25');
await page.locator('.milestone[aria-pressed=true]').filter({hasText:'ARIE invoering'}).waitFor();
await page.getByRole('button', {name:'Tijdlijn · lesdag 1',exact:true}).click();
await page.locator('.milestone[data-event-id=decision1997]').click();
await page.locator('.mini-step[data-mini-id=arie2023]').click();
await lessonRoutes.getByRole('button', {name:/Intern noodplan/}).click();
await page.locator('main h2').filter({hasText:/Intern noodplan/}).waitFor();
assert.equal(await page.getByLabel('Peildatum',{exact:true}).inputValue(),'2023-01-01');
await page.locator('.milestone[aria-pressed=true]').filter({hasText:'ARIE herziening'}).waitFor();
await page.getByRole('button', {name:'Tijdlijn · lesdag 1',exact:true}).click();
await page.locator('.milestone[data-event-id=law1999]').click();
await page.locator('.mini-step[data-mini-id=prevention2005]').click();
await lessonRoutes.getByRole('button', {name:/Deskundige werknemers/}).click();
await page.locator('main h1').filter({hasText:/Artikel 13/}).waitFor();
await page.locator('.legal-text').getByText('deskundige werknemers', {exact:false}).first().waitFor();
assert.equal(await page.getByLabel('Peildatum',{exact:true}).inputValue(),'2005-07-01');
await page.getByRole('button', {name:'Tijdlijn · lesdag 1',exact:true}).click();
await page.locator('.milestone[data-event-id=eu1989]').click();
await page.locator('.mini-step[data-mini-id=implement1994]').click();
assert.equal(await lessonRoutes.getByRole('button').count(), 3);
await lessonRoutes.getByRole('button', {name:/RI&E →/}).click();
assert.equal(await page.getByLabel('Peildatum',{exact:true}).inputValue(),'2026-10-05');
await page.locator('main h2').filter({hasText:/Inventarisatie/}).waitFor();
await page.getByRole('button', {name:'Tijdlijn · lesdag 1',exact:true}).click();
await page.locator('.milestone[data-event-id=change2007]').click();
assert.match(await page.locator('.event-topics').textContent(), /PSA/);
await page.locator('.milestone[data-event-id=care2017]').click();
assert.match(await page.locator('.event-topics').textContent(), /Basiscontract/);
assert.equal(await lessonRoutes.getByRole('button').count(), 2);
assert.equal(await page.locator('.teacher-answer').count(), 0);
await page.locator('.timeline-view').screenshot({path:fileURLToPath(new URL('arbozorg-lesdag-1.png',shots))});
await page.locator('.milestone[data-event-id=decision1997]').click();
await page.locator('.mini-step[data-mini-id=arie2023]').click();
await assertCardsFit();
await page.locator('.timeline-view').screenshot({path:fileURLToPath(new URL('tijdlijn-dag-1-herzien.png',shots))});
await page.getByRole('button', {name:'Presenteren',exact:true}).click();
await assertCardsFit();
await page.keyboard.press('Escape');
await page.setViewportSize({width:390,height:844});
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'Revised lesson overflows mobile viewport');
await assertCardsFit();
await page.getByRole('button', {name:/^Alle stappen/}).click();
assert.equal(await page.locator('.milestone').count(),17);
await assertCardsFit();
await page.screenshot({path:fileURLToPath(new URL('tijdlijn-dag-1-herzien-mobiel.png',shots)),fullPage:true});
// Incident cases form a separate lane and never change the legal milestone count.
await page.setViewportSize({width:1440,height:1100});
await page.getByRole('button',{name:/^Hoofdmijlpalen/}).click();
assert.equal(await page.locator('.incident-step').count(),4);
assert.equal(await page.locator('.responsibility-phase').count(),3);
assert.match(await page.locator('.development-note summary').textContent(),/overheid blijft regels stellen en toezicht houden/);
await page.locator('.incident-step[data-incident-id=seveso1976]').click();
assert.match(await page.locator('.event-explanation h2').textContent(),/^Seveso$/);
assert.match(await page.locator('.event-fact').textContent(),/1982/);
assert.equal(await page.locator('.milestone').count(),9);
assert.equal(await page.locator('.mini-step').count(),0);
assert.equal(await page.locator('.teacher-answer').count(),0);
await page.getByRole('button',{name:'Open docentantwoord',exact:true}).click();
await page.locator('.teacher-answer').waitFor();
await page.locator('.incident-step[data-incident-id=seveso1976]').focus();
await page.keyboard.press('ArrowLeft');
assert.match(await page.locator('.event-explanation h2').textContent(),/^DSM Beek$/);
assert.equal(await page.locator('.teacher-answer').count(),0);
await page.locator('.timeline-sources summary').click();
const caseSource=page.locator('.timeline-sources a').filter({hasText:'Lokaal bronbestand'});
assert.equal((await page.request.get(new URL(await caseSource.getAttribute('href'),base).href)).status(),200);
await page.locator('.parent-route button').click();
assert.equal(await page.locator('.incident-step[aria-pressed=true]').count(),0);
assert.match(await page.locator('.event-explanation h2').textContent(),/ARIE herziening/);
assert.equal(await page.locator('.mini-step').count(),3);
await page.locator('.milestone[data-event-id=law1980]').click();
await page.locator('.incident-step[data-incident-id=seveso1976]').click();
await assertCardsFit();
await page.locator('.timeline-view').screenshot({path:fileURLToPath(new URL('tijdlijn-incidenten.png',shots))});
await page.getByRole('button',{name:'Presenteren',exact:true}).click();
await assertCardsFit();
await page.locator('.incident-step[data-incident-id=moerdijk2011]').click();
assert.match(await page.locator('.event-explanation h2').textContent(),/Chemie-Pack/);
await page.screenshot({path:fileURLToPath(new URL('tijdlijn-incidenten-presentatie.png',shots)),fullPage:true});
await page.keyboard.press('Escape');
await page.setViewportSize({width:390,height:844});
await page.locator('.incident-step[data-incident-id=enschede2000]').click();
assert.equal(await page.locator('.horizontal-track').evaluate(track=>{
  const bounds=track.getBoundingClientRect();
  const selected=track.querySelector('.milestone[aria-pressed=true]').getBoundingClientRect();
  return selected.left>=bounds.left-1&&selected.right<=bounds.right+1;
}),true,'Selected milestone left off screen after resizing');
assert.match(await page.locator('.event-explanation h2').textContent(),/Enschede/);
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'Incident lane overflows mobile viewport');
await assertCardsFit();
await page.screenshot({path:fileURLToPath(new URL('tijdlijn-incidenten-mobiel.png',shots)),fullPage:true});
// The newly revealed card stays visible at phone width, also while presenting.
await page.getByRole('button',{name:'Opnieuw beginnen ↺',exact:true}).click();
assert.equal(await page.locator('.milestone').count(),1);
await page.locator('.milestone[data-event-id=mine1810]').click();
assert.equal(await page.locator('.milestone').count(),2);
assert.equal(await page.locator('.horizontal-track').evaluate(track=>{
  const bounds=track.getBoundingClientRect(),card=track.querySelector('.just-revealed').getBoundingClientRect();
  return card.left>=bounds.left-1&&card.right<=bounds.right+1;
}),true,'Newly revealed card is off screen on mobile');
await assertCardsFit();
await page.getByRole('button',{name:'Presenteren',exact:true}).click();
await page.locator('.milestone[data-event-id=child1874]').click();
assert.equal(await page.locator('.milestone').count(),3);
await assertCardsFit();
await page.screenshot({path:fileURLToPath(new URL('tijdlijn-opbouw-mobiel.png',shots)),fullPage:true});
await page.keyboard.press('Escape');
assert.deepEqual(errors, []);
assert.deepEqual(failures, []);
assert.deepEqual(external, [], 'Application requested an external runtime asset');
await browser.close();
const report = { status: 'passed', desktop: '1440 × 1100', mobile: '390 × 844', lesson_events: 17, major_milestones: 9, smaller_steps: 8, incident_cases:4, development_phases:3,
  checks: ['major-only default and all-steps filter', 'nested selection keeps parent highlighted', 'mini timeline keyboard and return to parent', '1980/1983 and 1989/1994 drilldown', 'official publication/effective mini timeline', 'unknown legal impact remains visible', 'hidden and reset teacher answer', 'keyboard navigation', 'all card bounds', 'presentation and Escape',
    'law extent filter and preserved selection when switching regulations', 'cross-regulation ARIE subject search and article navigation', 'source-number search and no results', 'ARIE deep link', 'legal card bounds and mobile subject search', 'regulation switch', 'ARIE 2022/2023 date boundary', 'added and removed diff text', 'offline publication and raw XML',
    'article timeline sets effective date and opens offline source', 'mobile overflow', 'no external asset requests', 'no browser errors', '2004 and 2023 ARIE article numbering and dated text', '2005 preventive employee historical article', 'current RI&E core routes and PSA/basiscontract context', 'revised lesson desktop, mobile and presentation', 'four distinct incident cases, keyboard, answer reset, offline evidence and return to main milestone', 'qualitative development rail has no card overlap on desktop, mobile or presentation', 'fresh lesson shows only Mine Law; future cards, incident cases and keyboard routes hidden', 'one frontier click reveals one next card with animation; revisiting earlier cards preserves progress', 'restart, show all, chronological supplements, nine-milestone and seventeen-step build', 'reduced motion, arrow-key reveal and newly revealed card visible on mobile and presentation'],
  errors, failures, external };
await writeFile(new URL('browser-results.json', shots), JSON.stringify(report, null, 2) + '\n');
console.log(JSON.stringify(report, null, 2));
